# Supabase configuration for Neer Thuli
# Water Infrastructure Monitoring Platform

project_id = "rmwvhfmootqzcxjgblsq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
jwt_expiry = 3600
enable_signup = false
enable_email_confirmations = true
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://localhost:54322/auth/v1/callback"

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"

[edge_functions]
enabled = true
port = 54325

[analytics]
enabled = true
port = 54326
vector_port = 54327
# Setup your Database URL to report events
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

[functions.invite-user]
import_map = "./functions/import_map.json"
verify_jwt = true

[functions.cleanup-sessions]
import_map = "./functions/import_map.json"
verify_jwt = false

[db]
port = 54328
shadow_port = 54329
major_version = 15